services:
  - type: web
    name: portfolio-macdylan
    env: php
    plan: free
    buildCommand: composer install && php artisan migrate --force
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_NAME
        value: Portfolio
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://portfolio-macdylan.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: portfolio-db
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        fromDatabase:
          name: portfolio-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: portfolio-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: portfolio-db
          property: password
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: macdylankacou2000@gmail.com
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: macdylankacou2000@gmail.com
      - key: MAIL_FROM_NAME
        value: "Bokame Mac-Dylan KACOU"

  - type: pgsql
    name: portfolio-db
    plan: free
    ipAllowList: []
